{{- if .Values.web.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-web
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: web
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
    {{- range $key, $value := .Values.web.configMap.annotations }}
    {{ $key }}: {{ include "common.tplvalues.render" (dict "value" $value "context" $) | quote }}
    {{- end }}
data:
  {{- range $key, $value := .Values.web.configMap.data }}
  {{ $key }}: {{ include "common.tplvalues.render" (dict "value" $value "context" $) | quote }}
  {{- end }}
{{- end }}
