apiVersion: v1
data:
  gateway-ha-config.yml: |-
    {{ with .Values.gateway }}
    routingRules:
      rulesEngineEnabled: {{ .routingRules.enabled }}
      {{ if .routingRules.enabled }}
      rulesConfigPath: {{ .routingRules.configPath }}
      {{ end }}

    requestRouter:
      port: {{ .requestPort }}
      name: trinoRouter
      historySize: {{ .queryHistorySize }}
      requestBufferSize: 8192
    {{ end }}

    {{ with .Values.backendDatabase }}
    dataStore:
      jdbcUrl: jdbc:postgresql://{{ .host }}:{{ .port }}/{{ .schema }}
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      driver: org.postgresql.Driver
      queryHistoryHoursRetention: 24
    {{ end }}

    clusterStatsConfiguration:
      monitorType: INFO_API

    {{ with .Values.gateway }}
    server:
      applicationConnectors:
        - type: http
          port: {{ .appPort }}
          useForwardedHeaders: true
      adminConnectors:
        - type: http
          port: {{ .adminPort }}
          useForwardedHeaders: true
    {{ end }}

    modules:
      - io.trino.gateway.ha.module.HaGatewayProviderModule
      - io.trino.gateway.ha.module.ClusterStateListenerModule
      - io.trino.gateway.ha.module.ClusterStatsMonitorModule

    managedApps:
      - io.trino.gateway.ha.GatewayManagedApp
      - io.trino.gateway.ha.clustermonitor.ActiveClusterMonitor

    logging:
      type: external
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}-cm
