apiVersion: v2
name: composition-instance-gcp
description: Child account CRD helm chart

# Child account CRD helm chart
# this chart will create a resource kind: ChildAccountClaim that will use the child-account-composition chart
# link to the chart -> https://github.com/Ubix/ubix-charts/tree/main/charts/child-account-composition-gcp
# The CRD is defined by a crossplane composition and definition
# Additional information here: https://docs.crossplane.io/v1.10/reference/composition/

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.6

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"
