# Default values for compositioninstances.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#sample
metadata:
  name: #name to tag the created resources
spec:
  id: #value used to name the aws resources created like vpc, subnet, eks cluster, etc
  parameters:
    name: #customer account name, will also be injected in the aws root account email
    region: us-east-4
    providerconfig: "root-gcp"
  gke:
    version: 1.27.8-gke.1067004
    enabled: true
    maxClusterMemory: 2048
    maxClusterCpu: 1024
    maxClusterGpu: 16
