# Default values for compositioninstances.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#sample
metadata:
  name: #name to tag the created resources
spec:
  id: #value used to name the aws resources created like vpc, subnet, eks cluster, etc
  parameters:
    name: #customer account name, will also be injected in the aws root account email
    region: us-east-4
    providerconfig: "childaccount-gcp"
  gke:
    version: 1.29.1-gke.1589017