apiVersion: v1
data:
  {{- range $key, $val := .Values.hiveServerEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: {{ include "hiveMetastore.name" . }}
    {{- include "hiveMetastore.labels" . | nindent 4 }}
  name: hive-server-env