apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hive-server
  labels:
    app.kubernetes.io/name: {{ include "hiveMetastore.name" . }}
    app.kubernetes.io/component: server
    {{- include "hiveMetastore.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hiveMetastore.name" . }}
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  serviceName: hive-server
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hiveMetastore.name" . }}
        app.kubernetes.io/component: server
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      containers:
      - name: server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
#        command:
#          - /bin/bash
#          - /opt/hive/conf/startup.sh
        resources:
{{ toYaml .Values.resources | indent 10 }}
        envFrom:
          - configMapRef:
              name: hive-server-env
          - configMapRef:
              name: hive-env
        readinessProbe:
          httpGet:
            path: /
            port: 10002
          initialDelaySeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 10002
          initialDelaySeconds: 10
          timeoutSeconds: 2
#        volumeMounts:
#        - name: hive-config-server
#          mountPath: /opt/hive/conf
      volumes:
      - name: hive-config-server
        configMap:
          name: {{ include "hiveMetastore.fullname" . }}-server