apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: hive
    meta.helm.sh/release-namespace: dataspace
  labels:
    app.kubernetes.io/instance: hive
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.2.8
  name: hive-metastore-postgresql
spec:
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
    targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/instance: hive
    app.kubernetes.io/name: postgresql
    role: primary
  sessionAffinity: None
  type: ClusterIP