apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: childaccounts.tenant.resources
spec:
  connectionSecretKeys:
  - kubeconfig
  defaultCompositionRef:
    name: account-aws
  group: tenant.resources
  names:
    kind: ChildAccount
    plural: childaccounts
  claimNames:
    kind: ChildAccountClaim
    plural: childaccountclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
                description: ID of this Account that other objects will use to refer to it.
              parameters:
                type: object
                properties:
                  name:
                    description: Friendly name for the member account.
                    type: string
                  email:
                    description: Email address of the owner to assign to the new member account. This email address must not already be associated with another AWS account.
                    type: string
                  parentId:
                    description: Parent Organizational Unit ID or Root ID for the account. Defaults to the Organization default Root ID. A configuration must be present for this argument to perform drift detection.
                    type: string
                    default: ou-8jat-sv0412tm
                  region:
                    description: Region is the region you'd like your resource to be created in.
                    type: string
                    default: us-east-1
                  customerId:
                    description: Customer Identificaiton in Ubix
                    type: string
                required:
                - name
                - email
                - parentId
            required:
            - parameters
          status:
            type: object
            properties:
              id:
                description: The AWS account id
                type: string
              arn:
                description:  The ARN for this account.
                type: string
              accountStatus:
                description: The status of the AWS account
                type: string
              experimentalDataBucket:
                description: Experimental Data Bucket
                type: string
              warehouseBucket:
                description: Warehouse Bucket
                type: string
              bedrockRole:
                description: Bedrock IAM Role
                type: string
    additionalPrinterColumns:
    - name: AWSAccountID
      type: string
      jsonPath: ".status.id"
    - name: arn
      type: string
      jsonPath: ".status.arn"
    - name: accountStatus
      type: string
      jsonPath: ".status.accountStatus"
    - name: experimentalDataBucket
      type: string
      jsonPath: ".status.experimentalDataBucket"
    - name: warehouseBucket
      type: string
      jsonPath: ".status.warehouseBucket"
    - name: bedrockRole
      type: string
      jsonPath: ".status.bedrockRole"
