{
 "title": "Trino Cluster JMX",
 "description": "Trino deploy on k8s, collect jmx to monitor cluster",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(trino_execution_QueryManager_RunningQueries,app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster status overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of active workers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "trino_failuredetector_HeartbeatFailureDetector_ActiveCount{app='${cluster}'}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_failuredetector_HeartbeatFailureDetector_ActiveCount{app='${cluster}'} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_failuredetector_HeartbeatFailureDetector_ActiveCount{app='${cluster}'} offset 7d",
       "legendFormat": "{{app}}-seven days ago"
      }
     ]
    },
    {
     "title": "Number of blocked workers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "trino_memory_ClusterMemoryPool_BlockedNodes{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_BlockedNodes{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_BlockedNodes{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7 days ago"
      }
     ]
    },
    {
     "title": "Total number of CPU cores",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "trino_memory_ClusterMemoryManager_TotalAvailableProcessors{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_memory_ClusterMemoryManager_TotalAvailableProcessors{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_memory_ClusterMemoryManager_TotalAvailableProcessors{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-seven days ago"
      }
     ]
    },
    {
     "title": "Total Distributed Bytes (cluster memory pool)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_memory_ClusterMemoryPool_TotalDistributedBytes{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_TotalDistributedBytes{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_TotalDistributedBytes{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7 days ago"
      }
     ]
    },
    {
     "title": "Free Distributed Bytes (cluster memory pool)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_memory_ClusterMemoryPool_FreeDistributedBytes{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_FreeDistributedBytes{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_FreeDistributedBytes{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7 days ago"
      }
     ]
    },
    {
     "title": "Reserved Revocable Distributed Bytes (cluster memory pool)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_memory_ClusterMemoryPool_ReservedRevocableDistributedBytes{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_ReservedRevocableDistributedBytes{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_ReservedRevocableDistributedBytes{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7 days ago"
      }
     ]
    },
    {
     "title": "Reserved Distributed Bytes (cluster memory pool)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_memory_ClusterMemoryPool_ReservedDistributedBytes{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_ReservedDistributedBytes{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_ReservedDistributedBytes{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7 days ago"
      }
     ]
    },
    {
     "title": "Cluster User Memory Reservation (Running query usage sum)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_memory_ClusterMemoryManager_ClusterUserMemoryReservation{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_memory_ClusterMemoryManager_ClusterUserMemoryReservation{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_memory_ClusterMemoryManager_ClusterUserMemoryReservation{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7 days ago"
      }
     ]
    },
    {
     "title": "Cluster Total Memory Reservation (Running query usage total)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_memory_ClusterMemoryManager_ClusterTotalMemoryReservation{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_memory_ClusterMemoryManager_ClusterTotalMemoryReservation{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_memory_ClusterMemoryManager_ClusterTotalMemoryReservation{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7 days ago"
      }
     ]
    }
   ]
  },
  {
   "title": "Query execution overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Running queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "trino_execution_QueryManager_RunningQueries{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_execution_QueryManager_RunningQueries{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_execution_QueryManager_RunningQueries{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-seven days ago"
      }
     ]
    },
    {
     "title": "Queued query number",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "trino_execution_QueryManager_QueuedQueries{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_execution_QueryManager_QueuedQueries{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_execution_QueryManager_QueuedQueries{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-seven days ago"
      }
     ]
    },
    {
     "title": "Number of query submissions per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "increase(trino_execution_QueryManager_SubmittedQueries_TotalCount{app=~\"$cluster\"}[1m])",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "increase(trino_execution_QueryManager_SubmittedQueries_TotalCount{app=~\"$cluster\"}[1m] offset 1d) ",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "increase(trino_execution_QueryManager_SubmittedQueries_TotalCount{app=~\"$cluster\"}[1m] offset 7d) ",
       "legendFormat": "{{app}}-seven days ago"
      }
     ]
    },
    {
     "title": "Number of queries completed per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "targets": [
      {
       "expr": "increase(trino_execution_QueryManager_CompletedQueries_TotalCount{app=~\"$cluster\"}[1m])",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "increase(trino_execution_QueryManager_CompletedQueries_TotalCount{app=~\"$cluster\"}[1m] offset 1d)",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "increase(trino_execution_QueryManager_CompletedQueries_TotalCount{app=~\"$cluster\"}[1m] offset 7d)",
       "legendFormat": "{{app}}-seven days ago"
      }
     ]
    },
    {
     "title": "Number of failed queries per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "targets": [
      {
       "expr": "increase(trino_execution_QueryManager_FailedQueries_TotalCount{app=~\"$cluster\"}[1m])",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "increase(trino_execution_QueryManager_FailedQueries_TotalCount{app=~\"$cluster\"}[1m] offset 1d)",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "increase(trino_execution_QueryManager_FailedQueries_TotalCount{app=~\"$cluster\"}[1m] offset 7d)",
       "legendFormat": "{{app}}-seven days ago"
      }
     ]
    },
    {
     "title": "Total number of queries with memory leaks per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "increase(trino_memory_ClusterMemoryManager_NumberOfLeakedQueries{app=~\"$cluster\"}[1m])",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "increase(trino_memory_ClusterMemoryManager_NumberOfLeakedQueries{app=~\"$cluster\"}[1m] offset 1d)",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "increase(trino_memory_ClusterMemoryManager_NumberOfLeakedQueries{app=~\"$cluster\"}[1m] offset 7d)",
       "legendFormat": "{{app}}-seven days ago"
      }
     ]
    },
    {
     "title": "Total number of queries oom killed per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "increase(trino_memory_ClusterMemoryManager_QueriesKilledDueToOutOfMemory{app=~\"$cluster\"}[1m])",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "increase(trino_memory_ClusterMemoryManager_QueriesKilledDueToOutOfMemory{app=~\"$cluster\"}[1m] offset 1d)",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "increase(trino_memory_ClusterMemoryManager_QueriesKilledDueToOutOfMemory{app=~\"$cluster\"}[1m] offset 7d)",
       "legendFormat": "{{app}}-seven days ago"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Execution Scheduling Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average of Task(Finished)Cpu time consumption in the last minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_CpuTime_OneMinute_Avg{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_CpuTime_OneMinute_Avg{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_CpuTime_OneMinute_Avg{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7 days ago"
      }
     ]
    },
    {
     "title": "The maximum value of Task(Finished)Cpu consumption in the last minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_CpuTime_OneMinute_Max{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_CpuTime_OneMinute_Max{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_CpuTime_OneMinute_Max{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7 days ago"
      }
     ]
    },
    {
     "title": "The average execution time of Task(Finished) in the last minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_ElapsedTime_OneMinute_Avg{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_ElapsedTime_OneMinute_Avg{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_ElapsedTime_OneMinute_Avg{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7 days ago"
      }
     ]
    },
    {
     "title": "The maximum execution time of Task(Finished) in the last minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_ElapsedTime_OneMinute_Max{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_ElapsedTime_OneMinute_Max{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_ElapsedTime_OneMinute_Max{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7 days ago"
      }
     ]
    },
    {
     "title": "Task(Finished)InputBlockedTime average value in the last minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_InputBlockedTime_OneMinute_Avg{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_InputBlockedTime_OneMinute_Avg{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_InputBlockedTime_OneMinute_Avg{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7 days ago"
      }
     ]
    },
    {
     "title": "Maximum value of Task(Finished)InputBlockedTime in the last minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_InputBlockedTime_OneMinute_Max{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_InputBlockedTime_OneMinute_Max{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_InputBlockedTime_OneMinute_Max{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7 days ago"
      }
     ]
    },
    {
     "title": "Task(Finished)OutputBlockedTime average value in the last minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_OutputBlockedTime_OneMinute_Avg{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_OutputBlockedTime_OneMinute_Avg{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_OutputBlockedTime_OneMinute_Avg{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7 days ago"
      }
     ]
    },
    {
     "title": "Maximum value of Task(Finished)OutputBlockedTime in the last minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_OutputBlockedTime_OneMinute_Max{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_OutputBlockedTime_OneMinute_Max{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_OutputBlockedTime_OneMinute_Max{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7 days ago"
      }
     ]
    },
    {
     "title": "Task(Finished)PeakMemoryReservation average value in the last minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_PeakMemoryReservationInBytes_OneMinute_Avg{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_PeakMemoryReservationInBytes_OneMinute_Avg{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_PeakMemoryReservationInBytes_OneMinute_Avg{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7 days ago"
      }
     ]
    },
    {
     "title": "Maximum value of Task(Finished)PeakMemoryReservation in the last minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_PeakMemoryReservationInBytes_OneMinute_Max{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_PeakMemoryReservationInBytes_OneMinute_Max{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_PeakMemoryReservationInBytes_OneMinute_Max{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7 days ago"
      }
     ]
    },
    {
     "title": "Task Descriptor Storage Reserved Bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskDescriptorStorage_ReservedBytes{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_execution_scheduler_TaskDescriptorStorage_ReservedBytes{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_execution_scheduler_TaskDescriptorStorage_ReservedBytes{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7 days ago"
      }
     ]
    }
   ]
  },
  {
   "title": "Overview of recently completed Query data processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "The cumulative number of bytes processed by Query in the past minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(trino_execution_QueryManager_ConsumedInputBytes_TotalCount{app=~\"$cluster\"}[1m])",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "increase(trino_execution_QueryManager_ConsumedInputBytes_TotalCount{app=~\"$cluster\"}[1m] offset 1d)",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "increase(trino_execution_QueryManager_ConsumedInputBytes_TotalCount{app=~\"$cluster\"}[1m] offset 7d)",
       "legendFormat": "{{app}}-seven days ago"
      }
     ]
    },
    {
     "title": "The cumulative value of QueryCPU time taken to complete in the past minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(trino_execution_QueryManager_ConsumedCpuTimeSecs_TotalCount{app=~\"$cluster\"}[1m])",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "increase(trino_execution_QueryManager_ConsumedCpuTimeSecs_TotalCount{app=~\"$cluster\"}[1m] offset 1d)",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "increase(trino_execution_QueryManager_ConsumedCpuTimeSecs_TotalCount{app=~\"$cluster\"}[1m] offset 7d)",
       "legendFormat": "{{app}}-seven days ago"
      }
     ]
    },
    {
     "title": "Average rate of Query data processing completed in the past minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "trino_execution_QueryManager_WallInputBytesRate_OneMinute_Avg{app=~\"$cluster\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_execution_QueryManager_WallInputBytesRate_OneMinute_Avg{app=~\"$cluster\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_execution_QueryManager_WallInputBytesRate_OneMinute_Avg{app=~\"$cluster\"} offset 7d",
       "legendFormat": "{{app}}-seven days ago"
      }
     ]
    },
    {
     "title": "Maximum completion rate of Query data processing in the past minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "trino_execution_QueryManager_WallInputBytesRate_OneMinute_Max{app=~\"$cluster\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_execution_QueryManager_WallInputBytesRate_OneMinute_Max{app=~\"$cluster\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_execution_QueryManager_WallInputBytesRate_OneMinute_Max{app=~\"$cluster\"} offset 7d",
       "legendFormat": "{{app}}-seven days ago"
      }
     ]
    },
    {
     "title": "Average execution time of Query completed in the past minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_QueryManager_ExecutionTime_OneMinute_Avg{app=~\"$cluster\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_execution_QueryManager_ExecutionTime_OneMinute_Avg{app=~\"$cluster\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_execution_QueryManager_ExecutionTime_OneMinute_Avg{app=~\"$cluster\"} offset 7d",
       "legendFormat": "{{app}}-seven days ago"
      }
     ]
    },
    {
     "title": "Maximum execution time of Query in the past minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_QueryManager_ExecutionTime_OneMinute_Max{app=~\"$cluster\"}",
       "legendFormat": "{{app}}-Today"
      },
      {
       "expr": "trino_execution_QueryManager_ExecutionTime_OneMinute_Max{app=~\"$cluster\"} offset 1d",
       "legendFormat": "{{app}}-yesterday"
      },
      {
       "expr": "trino_execution_QueryManager_ExecutionTime_OneMinute_Max{app=~\"$cluster\"} offset 7d",
       "legendFormat": "{{app}}-seven days ago"
      }
     ]
    }
   ]
  }
 ]
}