{{- if .Values.worker.priorityClass.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.worker.priorityClass.name }}-worker
value: {{ default 1000000 .Values.worker.priorityClass.value }}
globalDefault: {{ default false .Values.worker.priorityClass.globalDefault }}
{{- if .Values.worker.priorityClass.description }}
description: {{ .Values.worker.priorityClass.description }}
{{- end }}
{{- end }}
