---
# Similarly you can use a ClusterRole and ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "account-provisioner.fullname" .}}
rules:
  - apiGroups:
      - "*"
    verbs:
      - "*"
    resources:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "account-provisioner.fullname" .}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "account-provisioner.fullname" .}}
subjects:
  - kind: ServiceAccount
    name: {{ include "account-provisioner.fullname" .}}
    namespace: {{ .Release.Namespace }}
