{{- if .Values.secrets.enabled }}
{{- $root := . -}}  {{/* Capture the root context */}}
{{- range $secretName, $secretData := .Values.secrets.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "account-provisioner.fullname" $ }}-{{ $secretName }}
  namespace: {{ default $root.Release.Namespace $root.Values.namespaceOverride }}
  labels:
    {{- include "account-provisioner.labels" $ | nindent 4 }}
    {{- with $root.Values.secrets.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $root.Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $value := $secretData }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}
{{- end }}
