apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "account-provisioner.fullname" . }}
  labels:
    {{- include "account-provisioner.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

