apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: childaccount.gcp.ubix.io
spec:
  connectionSecretKeys:
  - kubeconfig
  # defaultCompositionRef:
  #   name: account-aws
  group: gcp.ubix.io
  names:
    kind: ChildAccount
    plural: childaccount
  claimNames:
    kind: ChildAccountClaim
    plural: childaccountclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
                description: ID of this Account that other objects will use to refer to it.
              parameters:
                type: object
                properties:
                  name:
                    description: Friendly name for the member project.
                    type: string
                  parentId:
                    description: Parent Organizational Unit ID or Root ID for the account. Defaults to the Organization default Root ID. A configuration must be present for this argument to perform drift detection.
                    type: string
                  billingAccount:
                    description: The billing account this project belongs to.
                    type: string
                  region:
                    description: Region is the region you'd like your resource to be created in.
                    type: string
                    default: us-east-1
                  AWSNATIP:
                    description: the NAT IP address which is used by EKS Cluster where ArgoCD is running
                    type: string
                required:
                - name
                - parentId
                - billingAccount
                - AWSNATIP
              gke:
                type: object
                properties:
                  version:
                    description: The Kubernetes version for the cluster.
                    type: string
                    default: "1.27.3-gke.100"
            #       vpcCniAddonVersion:
            #         description: The VPC CNI Addon version to install in the cluster.
            #         type: string
            #         default: "v1.11.4-eksbuild.1"
            #       nodeSize:
            #         description: The size of the nodes; small, medium, large
            #         type: string
            #         default: small
            #       minNodeCount:
            #         description: The minimum number of nodes
            #         type: integer
            #         default: 1
            #       maxNodeCount:
            #         description: The maximum number of nodes
            #         type: integer
            #         default: 3
            #       desiredNodeCount:
            #         description: The desired number of nodes
            #         type: integer
            #         default: 1
            #       diskSize:
            #         description: The root device disk size (in GiB) for your node group instances. The default disk size is 20 GiB.
            #         type: integer
            #         default: 20
            required:
            - parameters
          status:
            type: object
            properties:
              id:
                description: The GCP project id
                type: string
              projectNumber:
                description: The GCP project number
                type: string
              vpcID:
                description: The VPC id
                type: string
              projectStatus:
                description: The status of the GCP project
                type: string
              natGatewayStaticIPID:
                description: Nat Gateway static ip id
                type: string
              natGatewayRouterID:
                description: Nat Gateway Router id
                type: string
              natGatewayID:
                description: id of the nat gateway
                type: string
              natGatewayIP:
                description: ip of the nat gateway
                type: string
              privateSubnet1ID:
                description: id of the private subnet 1
                type: string
              kmsKeyringID:
                description: id of the kms keyring
                type: string
              gkeKmsKeyID:
                description: id of the gke kms key
                type: string
              persistentDiskKmsKeyID:
                description: id of the persistent-disk kms key
                type: string
              gkeNodePoolSAEmail:
                description: email of the gke nodepool service-account
                type: string
              postgresOperatorGCSSAEmail:
                description: email of the postgres-operator-gcs-backups service-account
                type: string
              mlflowArtifactsSAEmail:
                description: email of the mlflow-artifacts service-account
                type: string
              apiServiceSAEmail:
                description: email of the api-service service-account
                type: string
              dataServiceSAEmail:
                description: email of the data-service service-account
                type: string
              dataServiceExternalSAEmail:
                description: email of the data-service-external service-account
                type: string
              dataFlowListenerSAEmail:
                description: email of the dataflow listener service-account
                type: string
              execServicePythonSAEmail:
                description: email of the execution service python service-account
                type: string
              dataLineageSAEmail:
                description: email of the data lineage service-account
                type: string
              gcsVeleroSAEmail:
                description: email of the gcs velero service-account
                type: string
              ALBSAEmail:
                description: email of the alb service-account
                type: string
              artifactRegistryID:
                description: id of the artifact registry
                type: string
              # nodeEgressIPv4FirewallRuleID:
              #   description: ID of the Firewall Rule to allow IPv4 Egress for GKE Nodes 
              #   type: string
              # nodeEgressIPv6FirewallRuleID:
              #   description: ID of the Firewall Rule to allow IPv6 Egress for GKE Nodes 
              #   type: string
              # efsSecurityGroupID:
              #   description: ID of the Security group for all EFS mount targets
              #   type: string
              # efsID:
              #   description: ID of the EFS file system
              #   type: string
              clusterName:
                description: The name of the cluster
                type: string
              controlPlaneStatus:
                description: The status of the control plane
                type: string
              # nodePoolStatus:
              #   description: The status of the node pool
              #   type: string
              # clusterOIDC:
              #   description: Issuer URL for the OpenID Connect identity provider.
              #   type: string
              clusterEndpoint:
                description: Endpoint for your Kubernetes API server.
                type: string
              clusterCertificateAuthorityData:
                description: Base64 encoded certificate data required to communicate with your cluster.
                type: string
              # vpcCniRoleArn:
              #   description: Role to attach to VPC CNI service account
              #   type: string
              # vpcCniRoleName:
              #   description: Role to attach to VPC CNI service account
              #   type: string
              # fargateExecRoleArn:
              #   description: Role to give fargate execution perms
              #   type: string
              # fargateExecRoleName:
              #   description: Role to give fargate execution perms
              #   type: string
              # karpenterIRSARoleArn:
              #   description: Role to give karpenter workload
              #   type: string
              # karpenterIRSARoleName:
              #   description: Role to give karpenter workload
              #   type: string
              # karpenterClusterRoleArn:
              #   description: Role to give karpenter workload
              #   type: string
              # karpenterClusterRoleName:
              #   description: Role to give karpenter workload
              #   type: string
              # karpenterIRSAPolicyArn:
              #   description: Policy to allow karpenter workload to work
              #   type: string
              # mlflowRoleName:
              #   description: Role to give s3 access to the cluster
              #   type: string
              # apiServiceRoleName:
              #   description: Role to give s3 access to the cluster
              #   type: string
              # ALBRoleName:
              #   description: Role to give load balancer controller access to the cluster
              #   type: string
              # postgresOperatorRoleName:
              #   description: Role that makes sure Postgres can send compressed WAL files to the given S3 bucket
              #   type: string
              # dataLineageRoleName:
              #   description: Role to give s3 access to the cluster
              #   type: string
              # dataServiceRoleName:
              #   description: Role to give s3 access to the cluster
              #   type: string
              # dataServiceExternalRoleName:
              #   description: Role to give s3 access to the cluster
              #   type: string
              # dataFlowListenerRoleName:
              #   description: Role to give s3 access to the cluster
              #   type: string
              # execServicePythonRoleName:
              #   description: Role to give s3 access to the cluster
              #   type: string
              # executionArtifactsS3PolicyArn:
              #   description: Policy to give s3 access to the cluster
              #   type: string
              # ingestionArtifactsS3PolicyArn:
              #   description: Policy to give s3 access to the cluster
              #   type: string
              # ingestionArtifactsS3WritePolicyArn:
              #   description: Policy to give s3 write access to the cluster
              #   type: string
              # mlflowArtifactsS3PolicyArn:
              #   description: Policy to give s3 access to the cluster
              #   type: string
              GCPLBGKERoleID:
                description: Role-id to give load balancer controller access to the cluster
                type: string
              # postgresOperatorS3PolicyArn:
              #   description: Policy to give s3 access to the cluster, bucket that is used for postgres s3 backups
              #   type: string
              # externalDnsRoleArn:
              #   description: Policy to allow external dns to work
              #   type: string
              # certManagerRoleArn:
              #   description: Policy to allow external dns to work
              #   type: string
              # externalDataUploadRoleArn:
              #   description: Role to upload data from dataspace
              #   type: string
              # dataspaceBackendRoleArn:
              #   description: Role to make dataspace send data to s3 bucket
              #   type: string
              zoneId:
                description: Zone id
                type: string
              zoneNameServers:
                description: Zone name servers
                type: array
                items:
                  type: string
                default: []
              ingestionArtifactsBucketName:
                description: GCS Bucket for Cloudspace apps
                type: string
              mlflowArtifactsBucketName:
                description: GCS Bucket for Cloudspace apps
                type: string
              executionArtifactsBucketName:
                description: GCS Bucket for Cloudspace apps
                type: string
              postgresBackupsBucketName:
                description: GCS Bucket for Postgres backups
                type: string
              # eksKmsArn:
              #   description: EKS KMS key
              #   type: string
              # ebsKmsArn:
              #   description: EBS csi driver KMS key
              #   type: string
              dnsAuthorizationID:
                description: dns authorization id for gcp certificate
                type: string
              GCMresourceRecordName:
                description: The name of the DNS record to create to validate the certificate
                type: string
              GCMresourceRecordValue:
                description: The type of DNS record to create
                type: string
              GCMresourceRecordType:
                description: The value the DNS record needs to have
                type: string
              certificateID:
                description: ID of the certificate that is being validated.
                type: string
    additionalPrinterColumns:
    - name: GCPProjectID
      type: string
      jsonPath: ".status.id"
    - name: projectStatus
      type: string
      jsonPath: ".status.projectStatus"
    # - name: clusterName
    #   type: string
    #   jsonPath: ".status.clusterName"
    # - name: controlPlane
    #   type: string
    #   jsonPath: ".status.controlPlaneStatus"
    # - name: nodePool
    #   type: string
    #   jsonPath: ".status.nodePoolStatus"
    # - name: clusterOIDC
    #   type: string
    #   jsonPath: ".status.clusterOIDC"
