{{- if .Values.autoRestore }}
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: {{ template "restore.name" . }}
  namespace: {{ .Values.veleroInstallNamespace }}
  annotations:
    # Ensure we run before sync phase
    argocd.argoproj.io/hook: PreSync
spec:
  backupName: ''
  scheduleName: {{ template "schedule.name" . }}
  existingResourcePolicy: update
  itemOperationTimeout: 1h
  includedResources:
    - 'PersistentVolumeClaim'
{{ include "includedNamespaces" . | indent 2 }}
{{ include "labelSelector" . | indent 2 }}
{{- end }}
