---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-pvc-cleanup-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  - "apps"
  resources:
  - persistentvolumeclaims
  - deployments
  - statefulsets
  verbs:
  - delete
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-wait-for-restore-role
rules:
- apiGroups:
  - velero.io
  resources:
  - restores
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-restore-job-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-pvc-cleanup-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-restore-job-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-pvc-cleanup-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-wait-for-restore-role-binding
  namespace: {{ .Values.veleroInstallNamespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-restore-job-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-wait-for-restore-role
  apiGroup: rbac.authorization.k8s.io
