apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ template "schedule.name" . }}
  namespace: {{ .Values.veleroInstallNamespace }}
spec:
  schedule: {{ .Values.backupScheduleCron }}
  template:
{{ include "includedNamespaces" . | indent 4 }}
{{ include "labelSelector" . | indent 4 }}
    includedResources:
    - 'PersistentVolumeClaim'
    snapshotVolumes: true
    ttl: {{ .Values.backupGarbageCollectionTTL }}
