apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ template "application.name" . }}
  namespace: {{ .Values.veleroNamesace }}
spec:
  schedule: {{ .Values.backupScheduleCron }}
  template:
    includedNamespaces:
    - {{ template "application.namespace" . }}
    includedResources:
    - 'PersistentVolumeClaim'
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: {{ template "application.name" . }}
    snapshotVolumes: true
    ttl: {{ .Values.backupGarbageCollectionTTL }}
    # Backup Action Hooks as defined in
    # https://velero.io/docs/latest/api-types/schedule/
    # https://velero.io/docs/latest/backup-hooks/
    hooks:
      resources: {{ .Values.backupHooks }}
      - name: mongodb-hook
        includedNamespaces:
        - {{ template "application.namespace" . }}
        includedResources:
        - pods
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: {{ template "application.name" . }}
        pre:
          - exec:
              container: mongodb
              command:
                - mongodump
                - /bitnami/mongodb/bkp
              onError: Fail
              timeout: 5m
