apiVersion: v1  
kind: Service  
metadata:  
  name: {{ include "eventstore.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "eventstore.name" . }}
    helm.sh/chart: {{ include "eventstore.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: database
spec:  
  selector:
    app.kubernetes.io/name: {{ include "eventstore.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: ext-tcp-port
      protocol: TCP
      port: {{ .Values.nodeTcpPort }}
      targetPort: {{ .Values.nodeTcpPort }}
    - name: int-tcp-port
      protocol: TCP
      port: {{ .Values.replicationPort }}
      targetPort: {{ .Values.replicationPort }}
    - name: http-port
      protocol: TCP
      port: {{ .Values.nodePort }}
      targetPort: {{ .Values.nodePort }}
  clusterIP: None
