# Velero install namespace
veleroInstallNamespace: addons
# The cron for running the backups
backupScheduleCron: 0 0,8,16 * * *
# The amount of time before backups created on this schedule are eligible for garbage collection.
# default here is 7 days, please respect this format when changing this value
backupGarbageCollectionTTL: 168h0m0s
# Enable auto restore from last backup
autoRestore: false
