---
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: Addon
metadata:
  name: "{{ include "cloudspace.name" .}}-coredns"
  labels:
    {{- include "cloudspace.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.region }}
    addonName: coredns
    addonVersion: {{ .Values.eks.addOns.coreDNSAddonVersion }}
    clusterNameRef:
      name: "{{ include "cloudspace.name" .}}-ekscluster"
  providerConfigRef:
    name: "{{ include "cloudspace.name" .}}-awsaccount-crossplane"
    policy:
      resolve: Always
---
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: Addon
metadata:
  name: "{{ include "cloudspace.name" .}}-aws-ebs-csi-driver"
  labels:
    {{- include "cloudspace.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.region }}
    addonName: aws-ebs-csi-driver
    addonVersion: {{ .Values.eks.addOns.awsEBSCSIDriverAddonVersion }}
    clusterNameRef:
      name: "{{ include "cloudspace.name" .}}-ekscluster"
  providerConfigRef:
    name: "{{ include "cloudspace.name" .}}-awsaccount-crossplane"
    policy:
      resolve: Always
---
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: Addon
metadata:
  name: "{{ include "cloudspace.name" .}}-kube-proxy"
  labels:
    {{- include "cloudspace.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.region }}
    addonName: kube-proxy
    addonVersion: {{ .Values.eks.addOns.kubeProxyAddonVersion }}
    clusterNameRef:
      name: "{{ include "cloudspace.name" .}}-ekscluster"
  providerConfigRef:
    name: "{{ include "cloudspace.name" .}}-awsaccount-crossplane"
    policy:
      resolve: Always
