apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: "{{ include "cloudspace.name" .}}-awsaccount-crossplane"
  labels:
    {{- include "cloudspace.labels" . | nindent 4 }}
spec:
  assumeRole:
    roleARN: "arn:aws:iam::{{ .Values.AWSAccountID}}:role/OrganizationAccountAccessRole"
  credentials:
    source: Secret
    secretRef:
      namespace: {{ .Values.providerConfig.secretRef.namespace }}
      name: {{ .Values.providerConfig.secretRef.name }}
      key: {{ .Values.providerConfig.secretRef.key }}
