---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: "{{ include "cloudspace.name" .}}rtb1"
  labels:
    {{- include "cloudspace.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.region }}
    associations:
      - subnetIdRef:
          name: "{{ include "cloudspace.name" .}}-ubix-subnet1"
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: "{{ include "cloudspace.name" .}}-igw"
    vpcIdRef:
      name: "{{ include "cloudspace.name" .}}-ubix-vpc"
  providerConfigRef:
    name: "{{ include "cloudspace.name" .}}-awsaccount-crossplane"
    policy:
      resolve: Always
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: "{{ include "cloudspace.name" .}}rtb2"
  labels:
    {{- include "cloudspace.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.region }}
    associations:
      - subnetIdRef:
          name: "{{ include "cloudspace.name" .}}-ubix-subnet2"
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: "{{ include "cloudspace.name" .}}-igw"
    vpcIdRef:
      name: "{{ include "cloudspace.name" .}}-ubix-vpc"
  providerConfigRef:
    name: "{{ include "cloudspace.name" .}}-awsaccount-crossplane"
    policy:
      resolve: Always
