{{- range $nodeClassName, $nodeClassSpecs := .Values.nodeClass }}
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ $nodeClassName }}
spec:
  amiFamily: {{ default "AL2" $nodeClassSpecs.amiFamily }}
  amiSelectorTerms:
{{ toYaml $nodeClassSpecs.amiSelector | indent 4 }}
  subnetSelectorTerms:
  - tags:
{{ $nodeClassSpecs.subnetSelectorTags | toYaml | indent 6}}
  securityGroupSelectorTerms:
  - tags:
{{ $nodeClassSpecs.securityGroupSelectorTags | toYaml | indent 6 }}
  instanceProfile: "{{ $nodeClassSpecs.instanceProfile }}"
  tags:
{{ $nodeClassSpecs.tags | toYaml | indent 4}}
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: {{ $nodeClassSpecs.volumeSize }}
        volumeType: gp3
        deleteOnTermination: true
{{- end }}
