apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}-collector
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-collector
  namespace: {{ .Release.Namespace }}
