apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Release.Name }}
spec:
  mode: {{ .Values.mode -}}
  {{ if eq .Values.mode "daemonset" }}
  priorityClassName: system-cluster-critical
  tolerations:
  - operator: Exists
  {{- end }}
  config: |-
{{ .Values.config | toYaml | indent 4 }}
