apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Release.Name }}
spec:
  mode: {{ .Values.mode -}}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: eks.amazonaws.com/compute-type
            operator: NotIn
            values:
            - fargate
  {{ if eq .Values.mode "daemonset" }}
  priorityClassName: system-cluster-critical
  tolerations:
  - effect: NoSchedule
    operator: Exists
  {{- end }}
  config: |-
{{ .Values.config | toYaml | indent 4 }}
