apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Release.Name }}
spec:
  mode: {{ .Values.mode }}
  config: |
{{ .Values.config | indent 4 | replace "basic_auth_token" .Values.basic_auth_token}}
