apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Release.Name }}
spec:
  mode: {{ .Values.mode }}
  priorityClassName: system-cluster-critical
  tolerations:
  - operator: Exists
  config: |-
{{ .Values.config | toYaml | indent 4 }}
