nameOverride: ""
fullnameOverride: ""
namespace: ""

eventBus:
  replicas: 1

eventSource:
  amqpUrl: amqp://rabbitmq-backoffice.databases.svc.cluster.local:5672
  exchange: create-account
  queue: create-account
  routingKey: create-account
  auth:
    secretName: account-provisioner-envs
    usernameKey: BROKER_USER
    passwordKey: BROKER_PASSWORD

clusterWorkflowTemplate:
  metadata:
    name: renew-sso-client
  entrypoint:
    name: renew-sso-client-workflow
  parameters:
    accounts: "[]"
    applications: "[]" 
  command:
    - python
    - -m
    - cmd.renew_sso_client_secrets
  image:
    repository: 882490700787.dkr.ecr.us-east-1.amazonaws.com/account-provisioner
    tag: acount-provisioner-464

sensor:
  image:
    repository: 882490700787.dkr.ecr.us-east-1.amazonaws.com/account-provisioner
    tag: account-provisioner-464
  args:
    - python
    - -m
    - cmd.create_account
  brokerSecretName: rabbitmq-cluster-secret
  brokerSecretUserKey: username
  brokerSecretPasswordKey: password

serviceAccount:
  create: true
  annotations: {}
  additionalLabels: {}
  name: ""

configMaps:
  enabled: true
  additionalLabels: {}
  annotations: {}
  data:
    envs:
      BROKER_HOST: rabbitmq-backoffice.databases.svc.cluster.local
      BROKER_QUEUE: account-status
      BROKER_EXCHANGE: account-status
      BROKER_PORT: 5672
      GITHUB_PEM_FILE_PATH: /usr/src/app/account-provisioner.pem
      UBIX_DEPLOYEMNTS_REPO_OWNER: Ubix
      UBIX_DEPLOYEMNTS_REPO: ubix-deployments
      UBIX_CHILD_ACCOUNT_TEMPLATE_REPO: child-account-template
      UBIX_CHILD_ACCOUNT_TEMPLATE_REPO_OWNER: Ubix
      SSO_BASE_URL: https://sso.home-dev.ubix.io
      BACKOFFICE_SUBDOMAIN: home-dev
      ENV: NEW-DEV

secrets:
  enabled: true
  additionalLabels: {}
  annotations: {}
  data:
    envs:
      GITHUB_INSTALLATION_ID: "GIT_INSTALLATION_ID"
      GITHUB_APP_ID: "GIT_APP_ID"
      THANOS_AWS_ACCESS_KEY: "AWS_ACCESS_KEY_ID"
      THANOS_AWS_SECRET_KEY: "AWS_SECRET_ACCESS_KEY"
      THANOS_BUCKET: "THANOS_BUCKET"
      THANOS_BUCKET_ENDPOINT: "THANOS_BUCKET_ENDPOINT"
    pem:
      account-provisioner.pem: |-
        -----BEGIN CERTIFICATE-----
        SAMEPLECERTIFICATE
        ...
        -----END CERTIFICATE-----