apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: {{ .Values.rabbitmqClusterName }}-account-provisioner-account-status
spec:
  name: account-status
  autoDelete: false
  durable: false
  rabbitmqClusterReference:
    name: {{ .Values.rabbitmqClusterName }}
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: {{ .Values.rabbitmqClusterName }}-account-status
spec:
  name: account-status
  vhost: "/"
  type: fanout
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: {{ .Values.rabbitmqClusterName }}
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: {{ .Values.rabbitmqClusterName }}-account-status
spec:
  vhost: "/"
  source: account-status
  destination: account-status
  destinationType: queue
  rabbitmqClusterReference:
    name: {{ .Values.rabbitmqClusterName }}
