{{ $clusterName := .Values.clusterName}}
{{ range .Values.policies }}
apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: {{ $clusterName }}-{{ .name }}
spec:
{{ . | toYaml | indent 2 }}
  rabbitmqClusterReference:
    name: {{ $clusterName }}
{{ end }}