mode: daemonset # values: daemonset | deployment | statefulset
config: |
  receivers:
    jaeger:
      protocols:
        thrift_compact:
  processors:

  exporters:
    debug:

  service:
    pipelines:
      traces:
        receivers: [jaeger]
        processors: []
        exporters: [debug]
