apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hadoop.fullname" . }}-historyserver
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: historyserver
spec:
  selector:
    matchLabels:
      app: {{ include "hadoop.name" . }}
      release: {{ .Release.Name }}
      component: historyserver
  minAvailable: {{ .Values.hdfs.historyServer.pdbMinAvailable }}
