apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: {{ .Values.connect.name }}
  annotations:
    # allow usage of KafkaConnector CRDs
    strimzi.io/use-connector-resources: "true"
spec:
    {{- toYaml .Values.connect.spec | nindent 2 }}
