apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: {{ .Values.connector.name }}
spec:
{{- range .Values.connectors }}
  - name: {{ .name }}
    {{- toYaml .spec | nindent 4 }}
{{- end }}
